name: test
on:
  workflow_call:
    inputs:
      haxe:
        required: true
        type: string
      arch:
        required: true
        type: string
      sep:
        required: true
        type: string
      ext:
        required: true
        type: string
      os:
        required: true
        type: string

env:
  HXCPP_ARCH_FLAG: ${{ inputs.arch == 'Arm64' && 'HXCPP_ARM64' || format('HXCPP_M{0}', inputs.arch) }}

jobs:
  haxe:
    runs-on: ${{ inputs.os }}
    name: haxe
    defaults:
      run:
        working-directory: test/haxe
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/workflows/setup
        with:
          haxe: ${{ inputs.haxe }}
      - name: build
        run: |
          haxe -C ../../tools/cc -m Main --cpp bin -D destination=g++
          haxe -C ../../tools/hxcpp compile-cpp.hxml
          ulimit -n
          ulimit -n 256
          ulimit -n
          haxe compile.hxml -D ${{ env.HXCPP_ARCH_FLAG }} -D CXX=$(pwd)/../../tools/cc/bin/g++
      - name: run
        run: bin${{ inputs.sep }}TestMain

